// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "LocaleLayout": {
        "title": "Головна",
        "description": "Це головна сторінка нашого сайту.",
        "welcomeMessage": "Вітаю на нашому сайті!"
    },
    "Header-contact": {
        "contact": "Олександр 067-149-67-41"
    },
    "Navigation": {
        "home": "Головна",
        "ourWorks": "Наші роботи",
        "about": "Про нас",
        "contacts": "Контакти",
        "blog": "Блог",
        "reviews": "Відгуки"
    },
    "Hero": {
        "title": "Чому під замовлення?",
        "description": "Меблі на замовлення — мистецтво затишку та стилю. Створіть простір, що втілює вашу мрію, ідеально доповнює інтер’єр та наповнює дім гармонією.",
        "button": "Замовити"
    }
};
export default messages;