import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { useLocale } from 'next-intl';
import { Analytics } from "@vercel/analytics/next";
import { usePathname } from "@/i18n/navigation";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const baseUrl = 'https://t-mebel.com.ua';
const locales = ['uk', 'ru', 'en'];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = useLocale();
  const pathname = usePathname();

  function removeLangPrefix(path: string, locale: string): string {
    // Корень /ru => ''
    if (path === `/${locale}`) return '/';
    if (path.startsWith(`/${locale}/`)) return path.slice(locale.length + 1) || '/';
    return path;
  }
  const slugPath = removeLangPrefix(pathname, locale); // теперь slugPath: /service, /about, /

  // Собираем canonical
  const canonicalUrl = `${baseUrl}/${locale}${slugPath === '/' ? '/' : slugPath}`;
  // Пример: https://t-mebel.com.ua/uk/about

  // Собираем hreflang для каждой локали
  const hreflangs = locales.map(lang => ({
    hreflang: lang,
    href: `${baseUrl}/${lang}${slugPath === '/' ? '/' : slugPath}`,
  })).concat([
    { hreflang: 'x-default', href: `${baseUrl}/uk${slugPath === '/' ? '/' : slugPath}` }
  ]);

  return (
    <html lang={locale}>
      <head>
        {/* canonical */}
        <link rel="canonical" href={canonicalUrl} />
        {/* hreflang */}
        {hreflangs.map(link => (
          <link
            key={link.hreflang}
            rel="alternate"
            hrefLang={link.hreflang}
            href={link.href}
          />
        ))}
        {/* Google Tag Manager (отложенная загрузка) */}
        <script>
          {`
            
            let gtmScript = document.createElement("script");
            gtmScript.src = "https://www.googletagmanager.com/gtag/js?id=G-DSKK22XDCJ";
            gtmScript.async = true;
            document.head.appendChild(gtmScript);

            window.dataLayer = window.dataLayer || [];
            function gtag() { dataLayer.push(arguments); }
            gtag('js', new Date());
            gtag('config', 'G-DSKK22XDCJ');
        
    `}
        </script>
      </head>
      <body className={`${montserrat.variable}`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
